version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${MYSQL_FORWARD_PORT:-3306}:3306"
    volumes:
      - mysql:/var/lib/mysql
    command:
      - --character-set-client-handshake=OFF
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - app_network


volumes:
  mysql:

networks:
  app_network:
    driver: bridge
